import { TransactionCategory } from '@/types/transaction';

export const MODAL_EXPENSE_CATEGORIES: TransactionCategory[] = [
  {
    id: 'housing',
    name: 'Housing',
    icon: 'Home',
    color: '#FF6B6B',
  },
  {
    id: 'utilities',
    name: 'Utilities',
    icon: 'Wifi',
    color: '#4ECDC4',
  },
  {
    id: 'groceries',
    name: 'Groceries',
    icon: 'ShoppingBag',
    color: '#FFD166',
  },
  {
    id: 'transport',
    name: 'Transport',
    icon: 'Car',
    color: '#06D6A0',
  },
  {
    id: 'gas',
    name: 'Gas/Fuel',
    icon: 'Droplet',
    color: '#118AB2',
  },
  {
    id: 'fertilizers',
    name: 'Fertilizers',
    icon: 'Leaf',
    color: '#34D399',
  },
  {
    id: 'seeds',
    name: 'Seeds & Plants',
    icon: 'Sprout',
    color: '#22C55E',
  },
  {
    id: 'dining',
    name: 'Dining Out',
    icon: 'Utensils',
    color: '#EF476F',
  },
  {
    id: 'coffee',
    name: 'Coffee',
    icon: 'Coffee',
    color: '#073B4C',
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    icon: 'Film',
    color: '#7209B7',
  },
  {
    id: 'subscriptions',
    name: 'Subscriptions',
    icon: 'FileText',
    color: '#F15BB5',
  },
  {
    id: 'health',
    name: 'Health',
    icon: 'Heart',
    color: '#FF595E',
  },
  {
    id: 'fitness',
    name: 'Fitness',
    icon: 'Dumbbell',
    color: '#8AC926',
  },
  {
    id: 'shopping',
    name: 'Shopping',
    icon: 'ShoppingBag',
    color: '#1982C4',
  },
  {
    id: 'personal-care',
    name: 'Personal Care',
    icon: 'Smile',
    color: '#6A4C93',
  },
  {
    id: 'education',
    name: 'Education',
    icon: 'GraduationCap',
    color: '#FFCA3A',
  },
  {
    id: 'books',
    name: 'Books & Learning',
    icon: 'BookOpen',
    color: '#8AC926',
  },
  {
    id: 'travel',
    name: 'Travel',
    icon: 'Plane',
    color: '#118AB2',
  },
  {
    id: 'vacation',
    name: 'Vacation',
    icon: 'Umbrella',
    color: '#06D6A0',
  },
  {
    id: 'gifts',
    name: 'Gifts',
    icon: 'Gift',
    color: '#FF595E',
  },
  {
    id: 'donations',
    name: 'Donations',
    icon: 'HandHeart',
    color: '#7209B7',
  },
  {
    id: 'insurance',
    name: 'Insurance',
    icon: 'Shield',
    color: '#073B4C',
  },
  {
    id: 'taxes',
    name: 'Taxes',
    icon: 'Percent',
    color: '#F15BB5',
  },
  {
    id: 'bank-fees',
    name: 'Bank Fees',
    icon: 'CreditCard',
    color: '#8B5CF6',
  },
  {
    id: 'debt',
    name: 'Debt',
    icon: 'Landmark',
    color: '#64748B',
  },
  {
    id: 'other',
    name: 'Other',
    icon: 'MoreHorizontal',
    color: '#94A3B8',
  },
];

export const MODAL_INCOME_CATEGORIES: TransactionCategory[] = [
  {
    id: 'salary',
    name: 'Salary',
    icon: 'Briefcase',
    color: '#10B981',
  },
  {
    id: 'freelance',
    name: 'Freelance',
    icon: 'Laptop',
    color: '#8B5CF6',
  },
  {
    id: 'business',
    name: 'Business',
    icon: 'Building',
    color: '#F59E0B',
  },
  {
    id: 'investment',
    name: 'Investment',
    icon: 'TrendingUp',
    color: '#3B82F6',
  },
  {
    id: 'dividends',
    name: 'Dividends',
    icon: 'PieChart',
    color: '#6366F1',
  },
  {
    id: 'rental',
    name: 'Rental Income',
    icon: 'Home',
    color: '#EC4899',
  },
  {
    id: 'gift',
    name: 'Gift',
    icon: 'Gift',
    color: '#F43F5E',
  },
  {
    id: 'refund',
    name: 'Refund',
    icon: 'RefreshCw',
    color: '#84CC16',
  },
  {
    id: 'side-hustle',
    name: 'Side Hustle',
    icon: 'Zap',
    color: '#F97316',
  },
  {
    id: 'bonus',
    name: 'Bonus',
    icon: 'Award',
    color: '#8B5CF6',
  },
  {
    id: 'commission',
    name: 'Commission',
    icon: 'DollarSign',
    color: '#10B981',
  },
  {
    id: 'interest',
    name: 'Interest',
    icon: 'Percent',
    color: '#3B82F6',
  },
  {
    id: 'pension',
    name: 'Pension',
    icon: 'User',
    color: '#6366F1',
  },
  {
    id: 'social-security',
    name: 'Social Security',
    icon: 'Users',
    color: '#EC4899',
  },
  {
    id: 'other-income',
    name: 'Other Income',
    icon: 'MoreHorizontal',
    color: '#94A3B8',
  },
];
